baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Franotes'

ignoreLogs = ['warning-goldmark-raw-html']

pagination.pagerSize = 10

[params]
description = "Simply learning French and taking notes"
dateFormat = "Jan 2, 2006"

[taxonomies]
tags = "tags"
author = "authors"

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

