baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

pagination.pagerSize = 10

[params]
description = "The fastest blog"
dateFormat = "Jan 2, 2006"

[taxonomies]
tags = "tags"
author = "authors"

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'
