baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My French diary'

ignoreLogs = ['warning-goldmark-raw-html']

pagination.pagerSize = 2

[params]
description = "My blog about learning French"
dateFormat = "Jan 2, 2006"

[taxonomies]
tags = "tags"
author = "authors"

[build]
  [[build.cachebusters]]
    source = 'layouts/.*'
    target = 'css'

